Add inline to profile, and allow profiling of the pad; add script from Galeon for moz finding
git-svn-id: svn+ssh://mono-cvs.ximian.com/svn/monodevelop/trunk@626 b5faff8f-5bce-0310-b493-a43f95cdeebf

diff --git a/MonoDevelop/monodevelop b/MonoDevelop/monodevelop
--- a/MonoDevelop/monodevelop
+++ b/MonoDevelop/monodevelop
@@ -1,12 +1,22 @@
 #!/bin/bash
 
 if test -n "$MOZILLA_FIVE_HOME"; then
-        MOZILLA_HOME=$MOZILLA_FIVE_HOME
+	MOZILLA_HOME=$MOZILLA_FIVE_HOME
+elif [ -f /usr/lib/mozilla-1.5/chrome/comm.jar ]; then
+	MOZILLA_HOME=/usr/lib/mozilla-1.5
+elif [ -f /usr/local/mozilla/chrome/comm.jar ]; then
+	MOZILLA_HOME=/usr/local/mozilla
 elif [ -f /usr/lib/mozilla/chrome/comm.jar ]; then
-        MOZILLA_HOME=/usr/lib/mozilla
+	MOZILLA_HOME=/usr/lib/mozilla
+elif [ -f /opt/mozilla/chrome/comm.jar ]; then
+	MOZILLA_HOME=/opt/mozilla
+elif [ -f /usr/lib/mozilla-0.9.7/chrome/comm.jar ]; then
+	MOZILLA_HOME=/usr/lib/mozilla-0.9.7/
+elif [ -f /opt/gnome/lib/mozilla/chrome/comm.jar ]; then
+        MOZILLA_HOME=/opt/gnome/lib/mozilla/
 else
-        echo "Cannot find mozilla installation directory. Please set MOZILLA_FIVE_HOME to your mozilla directory"
-        exit
+	echo "Cannot find mozilla installation directory. Please set MOZILLA_FIVE_HOME to your mozilla directory"
+	exit 1
 fi
  
 LD_LIBRARY_PATH=$MOZILLA_HOME:$LD_LIBRARY_PATH
